import React from 'react';
import Link from 'next/link';
import { constructMetadata, SITE_CONFIG } from '@/lib/seo/metadata';
import { PublicNavbar, PublicFooter } from '@/components/layout/PublicNav';
import { generateBreadcrumbSchema } from '@/lib/seo/structuredData';
import { ShieldCheck, FileText, CheckCircle2 } from 'lucide-react';

export const metadata = constructMetadata({
  title: 'Terms of Service — Subconscious Log',
  description:
    'Terms of service for Subconscious Log: personal ownership of your dream entries, subscription and lifetime terms, acceptable use, and service boundaries.',
  path: '/terms',
  keywords: ['dream journal terms', 'Subconscious Log terms of service', 'user ownership dream writing'],
});

export default function TermsPage() {
  const breadcrumbsJson = generateBreadcrumbSchema([
    { name: 'Home', url: '/' },
    { name: 'Terms of Service', url: '/terms' },
  ]);

  return (
    <div className="min-h-screen bg-[var(--bg-primary)] text-[var(--text-primary)] flex flex-col justify-between selection:bg-[var(--accent-soft)]">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbsJson) }}
      />

      <PublicNavbar />

      <main className="pt-32 pb-24 max-w-4xl mx-auto px-6 md:px-10 w-full space-y-12">
        {/* Header */}
        <div className="space-y-4">
          <div className="inline-flex items-center gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-[var(--accent)]" />
            <span className="text-[10px] font-mono uppercase tracking-[0.24em] text-[var(--accent)]">
              Legal Agreement
            </span>
          </div>

          <h1 className="text-4xl sm:text-5xl font-display font-medium tracking-tight text-[var(--text-primary)]">
            Terms of Service
          </h1>

          <p className="text-xs font-mono text-[var(--text-muted)]">
            Effective Date: {SITE_CONFIG.effectiveDate} &middot; Last Updated: {SITE_CONFIG.lastUpdated}
          </p>
        </div>

        {/* Content Body */}
        <div className="p-8 sm:p-10 rounded-3xl bg-[var(--bg-card)] border border-[var(--border-default)] space-y-8 text-xs sm:text-sm text-[var(--text-secondary)] leading-relaxed font-light">
          <section className="space-y-3">
            <h2 className="text-lg font-display font-medium text-[var(--text-primary)]">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using Subconscious Log ({SITE_CONFIG.url}), operated by {SITE_CONFIG.legalEntityName} (&ldquo;Subconscious Log&rdquo;, &ldquo;we&rdquo;, &ldquo;our&rdquo;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-display font-medium text-[var(--text-primary)]">
              2. Nature of the Service (Non-Medical Disclaimer)
            </h2>
            <p>
              Subconscious Log is a personal reflective journaling software application designed for self-awareness, personal creativity, and dream recall.
            </p>
            <div className="p-4 rounded-2xl bg-[var(--bg-elevated)] border border-[var(--border-default)] font-mono text-xs text-[var(--text-primary)]">
              IMPORTANT: Subconscious Log does NOT provide medical, psychiatric, psychological, or clinical healthcare advice, therapy, or diagnosis. The reflective prompts and symbolic motifs generated by our AI are subjective contemplation exercises and should never substitute for professional medical or mental health evaluation.
            </div>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-display font-medium text-[var(--text-primary)]">
              3. 100% User Ownership of Journal Entries
            </h2>
            <p>
              You retain sole and exclusive intellectual property ownership of all written entries, notes, transcripts, and creative reflections that you submit to Subconscious Log.
            </p>
            <p>
              You grant Subconscious Log only a limited, non-exclusive license to host, store, and process your content strictly to the extent necessary to provide the Service to you (e.g., displaying your entries and generating requested AI reflections). We assert zero claim of copyright over your personal dreams.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-display font-medium text-[var(--text-primary)]">
              4. User Accounts & Security
            </h2>
            <p>
              You are responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account. You agree to notify us immediately at <a href={`mailto:${SITE_CONFIG.securityEmail}`} className="text-[var(--accent)] hover:underline font-mono">{SITE_CONFIG.securityEmail}</a> if you detect unauthorized access.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-display font-medium text-[var(--text-primary)]">
              5. Plans, Billing, &amp; Lifetime Entitlements
            </h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Free Tier:</strong> Provided free of charge forever. Includes unlimited dream journal recording, calendar views, search, and 5 AI reflections per month.</li>
              <li><strong>Pro Monthly Tier:</strong> Billed at $9 USD per month on a recurring monthly cycle via Stripe. Includes 100 AI operations per month.</li>
              <li><strong>Pro Annual Tier:</strong> Billed at $72 USD per year (equivalent to $6/month, representing a 33% discount) on a recurring annual cycle via Stripe. Includes all Pro entitlements.</li>
              <li><strong>Lifetime Tier:</strong> A single, one-time payment of $149 USD granting permanent Pro feature entitlements with no recurring fees. Includes a recurring fair-use allowance of 100 AI operations per calendar month.</li>
              <li><strong>Subscription Cancellation:</strong> Recurring subscriptions may be cancelled at any time via Settings &rarr; Subscription & Plan. Access remains active through the end of the paid billing period.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-display font-medium text-[var(--text-primary)]">
              6. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, {SITE_CONFIG.legalEntityName} and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of, or inability to use, the Service. The Service is provided on an &ldquo;AS IS&rdquo; and &ldquo;AS AVAILABLE&rdquo; basis without warranties of any kind.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-display font-medium text-[var(--text-primary)]">
              7. Governing Law & Dispute Resolution
            </h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of {SITE_CONFIG.jurisdiction}, without regard to conflict of law principles.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-display font-medium text-[var(--text-primary)]">
              8. Contact Information
            </h2>
            <p>
              Legal Inquiries: <a href={`mailto:${SITE_CONFIG.supportEmail}`} className="text-[var(--accent)] hover:underline font-mono">{SITE_CONFIG.supportEmail}</a><br />
              Operator: {SITE_CONFIG.legalEntityName}<br />
              Address: {SITE_CONFIG.registeredAddress}
            </p>
          </section>
        </div>
      </main>

      <PublicFooter />
    </div>
  );
}
